version: '3.9'
name: 'bom-stock'
services:
  db:
    container_name: dev_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin@cd123
      POSTGRES_USER: admin
      POSTGRES_DB: blog
      PGDATA: './postgres/data'
    ports:
      - 5432:5432